-- Quiz questions generated by AI during collection
CREATE TABLE quizzes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    context_item_id UUID NOT NULL REFERENCES context_items(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options JSONB NOT NULL,         -- ["option1", "option2", "option3", "option4"]
    correct_index SMALLINT NOT NULL, -- 0-based index into options array
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(context_item_id)         -- one quiz per article
);

-- User quiz attempts
CREATE TABLE quiz_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    quiz_id UUID NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    context_item_id UUID NOT NULL,  -- denormalized for quick lookups
    answered_index SMALLINT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    coins_earned INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, quiz_id)        -- one attempt per user per quiz
);

CREATE INDEX idx_quiz_results_user_item ON quiz_results(user_id, context_item_id);
